"""
Market Intelligence Brief Generator for Binance PortfolioPulse AI.
Synthesizes macro market trends, top movers, and exchange volume metrics into a standalone update
that does not require personal portfolio holdings.
"""
from typing import Dict, Any, List, Optional
from datetime import datetime, timezone


class MarketBrief:
    """Encapsulates a synthesized market brief."""

    def __init__(
        self,
        headline: str,
        sentiment: str,
        key_points: List[str],
        top_gainers: List[Dict[str, Any]],
        top_losers: List[Dict[str, Any]],
        metrics: Dict[str, Any],
        generated_at: Optional[str] = None,
    ):
        self.headline = headline
        self.sentiment = sentiment
        self.key_points = key_points
        self.top_gainers = top_gainers
        self.top_losers = top_losers
        self.metrics = metrics
        self.generated_at = generated_at or datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "headline": self.headline,
            "sentiment": self.sentiment,
            "generated_at": self.generated_at,
            "key_points": self.key_points,
            "top_gainers": self.top_gainers,
            "top_losers": self.top_losers,
            "metrics": self.metrics,
        }

    def to_markdown(self) -> str:
        sentiment_emoji = "🟢" if "BULL" in self.sentiment or "RISK_ON" in self.sentiment else "🟡"
        lines = [
            f"# 🌐 Binance Agent OS - Daily Market Brief",
            f"**Generated:** `{self.generated_at}` | **Market Sentiment:** {sentiment_emoji} **{self.sentiment.replace('_', '-')}**",
            "",
            f"## 📰 {self.headline}",
            "",
            "### 📌 Key Takeaways",
        ]
        for kp in self.key_points:
            lines.append(f"- {kp}")

        lines.extend([
            "",
            "### 🚀 Top Movers",
            "| Asset | Price | 24h Change | 24h Volume (USD) |",
            "| :--- | :--- | :--- | :--- |",
        ])
        for g in self.top_gainers:
            lines.append(f"| **{g['asset']}** (Gainer) | ${g['price']:,.4f} | 🟢 +{g['priceChangePercent']:.2f}% | ${g['volume24hUsd']:,.0f} |")
        for l in self.top_losers:
            lines.append(f"| **{l['asset']}** (Laggard) | ${l['price']:,.4f} | 🔴 {l['priceChangePercent']:.2f}% | ${l['volume24hUsd']:,.0f} |")

        lines.extend([
            "",
            "### 📊 Market Indicators & Exchange Activity",
            f"- **Tracked 24h Volume:** ${self.metrics.get('total_tracked_volume_usd', 0):,.0f} USD across active pairs",
            f"- **Average 24h Movement:** {self.metrics.get('average_24h_change_pct', 0.0):+.2f}% across watchlist",
            f"- **Market Sentiment:** {self.sentiment.replace('_', ' ')}",
            f"- **Benchmark Asset:** Bitcoin at ${self.metrics.get('btc_price', 0):,.2f} ({self.metrics.get('btc_change_24h', 0.0):+.2f}%)",
            "",
            "---",
            "*Generated by Binance PortfolioPulse AI • Powered by Binance Agent OS*",
        ])
        return "\n".join(lines)


class MarketBriefGenerator:
    """Combines live/mock Binance market data into a cohesive market brief."""

    @classmethod
    def generate(
        cls,
        watchlist: Optional[List[str]] = None,
        mode: Optional[str] = None,
    ) -> MarketBrief:
        from ..connectors.binance_api import BinanceAPIClient
        from ..utils.logger import logger

        overview = None
        if mode == "mock":
            from ..connectors.mock_provider import MockDataProvider
            mock = MockDataProvider()
            overview = mock.get_market_overview(watchlist)
        else:
            try:
                api = BinanceAPIClient()
                overview = api.get_market_overview(watchlist)
            except Exception as e:
                logger.error(f"Live Binance market overview query failed: {e}")
                raise ConnectionError(f"Unable to fetch real-time Binance market data: {e}")

        assets = {a["asset"]: a for a in overview.get("assets", [])}
        top_gainers = overview.get("top_gainers", [])
        top_losers = overview.get("top_losers", [])
        sentiment = overview.get("sentiment", "MODERATE_RISK_ON")
        total_vol = overview.get("total_tracked_volume_usd", 0.0)
        avg_change = overview.get("average_24h_change_pct", 0.0)

        btc = assets.get("BTC", {"price": 63450.0, "priceChangePercent": 3.15, "volume24hUsd": 1200000000.0})
        eth = assets.get("ETH", {"price": 2720.0, "priceChangePercent": -2.45, "volume24hUsd": 800000000.0})
        sol = assets.get("SOL", {"price": 164.8, "priceChangePercent": 9.42, "volume24hUsd": 450000000.0})

        top_g = top_gainers[0] if top_gainers else {"asset": "SOL", "priceChangePercent": 9.42, "price": 164.80, "volume24hUsd": 450000000.0}

        # 1. Headline
        if btc.get("priceChangePercent", 0) >= 0:
            headline = (
                f"Crypto Markets Advance: {top_g['asset']} (+{top_g['priceChangePercent']:.1f}%) "
                f"and Altcoins Rally as BTC Holds ${btc['price']:,.0f}"
            )
        else:
            headline = (
                f"Market Choppiness: BTC Tests ${btc['price']:,.0f} While {top_g['asset']} "
                f"Defies Trend with +{top_g['priceChangePercent']:.1f}% Surge"
            )

        # 2. Key Points
        gainers_str = ", ".join(f"{g['asset']} (+{g['priceChangePercent']:.1f}%)" for g in top_gainers[:2])
        losers_str = ", ".join(f"{l['asset']} ({l['priceChangePercent']:.1f}%)" for l in top_losers) if top_losers else "None"

        key_points = [
            f"Bitcoin (BTC) is trading at ${btc['price']:,.2f} ({btc['priceChangePercent']:+.2f}%), consolidating with 24h volume of ${btc.get('volume24hUsd', 0):,.0f}.",
            f"Top performers: {gainers_str} demonstrate strong selective momentum across Binance spot markets." if gainers_str else "Top assets remain range-bound across Binance spot markets.",
            f"Laggards: {losers_str} experienced localized pullback." if top_losers else "No major laggards detected on watchlist.",
            f"Binance 24h tracked exchange volume stands at ${total_vol:,.0f} USD across active pairs.",
            f"Market sentiment index sits at {sentiment.replace('_', ' ')} with an average 24h asset return of {avg_change:+.2f}%.",
        ]

        # 3. Compact Metrics
        metrics = {
            "btc_price": btc["price"],
            "btc_change_24h": btc["priceChangePercent"],
            "eth_price": eth.get("price", 0.0),
            "eth_change_24h": eth.get("priceChangePercent", 0.0),
            "sol_price": sol.get("price", 0.0),
            "sol_change_24h": sol.get("priceChangePercent", 0.0),
            "top_gainer_asset": top_g["asset"],
            "top_gainer_pct": top_g["priceChangePercent"],
            "total_tracked_volume_usd": total_vol,
            "average_24h_change_pct": avg_change,
        }

        return MarketBrief(
            headline=headline,
            sentiment=sentiment,
            key_points=key_points,
            top_gainers=top_gainers,
            top_losers=top_losers,
            metrics=metrics,
        )
