"""
Market Intelligence Brief Generator for Binance PortfolioPulse AI.
Synthesizes macro market trends, top movers, and market price feed metrics into a standalone update
that does not require personal portfolio holdings.
"""
from typing import Dict, Any, List, Optional
from datetime import datetime, timezone

from ..connectors.mock_provider import MockDataProvider
from ..connectors.price_feed_data import PriceFeedDataProvider


class MarketBrief:
    """Encapsulates a synthesized market brief."""

    def __init__(
        self,
        headline: str,
        sentiment: str,
        key_points: List[str],
        top_gainers: List[Dict[str, Any]],
        top_losers: List[Dict[str, Any]],
        metrics: Dict[str, Any],
        generated_at: Optional[str] = None,
    ):
        self.headline = headline
        self.sentiment = sentiment
        self.key_points = key_points
        self.top_gainers = top_gainers
        self.top_losers = top_losers
        self.metrics = metrics
        self.generated_at = generated_at or datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "headline": self.headline,
            "sentiment": self.sentiment,
            "generated_at": self.generated_at,
            "key_points": self.key_points,
            "top_gainers": self.top_gainers,
            "top_losers": self.top_losers,
            "metrics": self.metrics,
        }

    def to_markdown(self) -> str:
        sentiment_emoji = "🟢" if "BULL" in self.sentiment or "RISK_ON" in self.sentiment else "🟡"
        lines = [
            f"# 🌐 Binance Agent OS - Daily Market Brief",
            f"**Generated:** `{self.generated_at}` | **Market Sentiment:** {sentiment_emoji} **{self.sentiment.replace('_', '-')}**",
            "",
            f"## 📰 {self.headline}",
            "",
            "### 📌 Key Takeaways",
        ]
        for kp in self.key_points:
            lines.append(f"- {kp}")

        lines.extend([
            "",
            "### 🚀 Top Movers",
            "| Asset | Price | 24h Change | 24h Volume (USD) |",
            "| :--- | :--- | :--- | :--- |",
        ])
        for g in self.top_gainers:
            lines.append(f"| **{g['asset']}** (Gainer) | ${g['price']:,.4f} | 🟢 +{g['priceChangePercent']:.2f}% | ${g['volume24hUsd']:,.0f} |")
        for l in self.top_losers:
            lines.append(f"| **{l['asset']}** (Laggard) | ${l['price']:,.4f} | 🔴 {l['priceChangePercent']:.2f}% | ${l['volume24hUsd']:,.0f} |")

        lines.extend([
            "",
            "### 📊 Market Indicators & Network Activity",
            f"- **BNB Chain:** {self.metrics.get('bnb_txs', '4.2M')} daily transactions | Gas: {self.metrics.get('bnb_gas', '3.0')} Gwei",
            f"- **Ethereum:** Gas at {self.metrics.get('eth_gas', '12.5')} Gwei | 24h DEX Volume: ${self.metrics.get('eth_dex_vol', '1.85B')}",
            f"- **DeFi Total TVL:** ${self.metrics.get('tvl_usd', '94.5B')} ({self.metrics.get('tvl_change', '+1.8%')} 24h)",
            f"- **Whale Flow:** {self.metrics.get('whale_signal', 'Net exchange outflow ($320M) - Accumulation detected')}",
            "",
            "---",
            "*Generated by Binance PortfolioPulse AI • Powered by Binance Agent OS*",
        ])
        return "\n".join(lines)


class MarketBriefGenerator:
    """Combines live/mock market data and price feed indicators into a cohesive market brief."""

    @classmethod
    def generate(
        cls,
        watchlist: Optional[List[str]] = None,
        mode: Optional[str] = None,
    ) -> MarketBrief:
        from ..connectors.binance_api import BinanceAPIClient
        from ..utils.logger import logger

        overview = None
        if mode != "mock":
            try:
                api = BinanceAPIClient()
                overview = api.get_market_overview(watchlist)
            except Exception as e:
                logger.warning(f"Live market overview query failed: {e}. Using benchmark overview.")

        if not overview or not overview.get("assets"):
            mock = MockDataProvider()
            overview = mock.get_market_overview(watchlist)

        price_feed_provider = PriceFeedDataProvider(mode="live" if mode != "mock" else "mock")
        price_feeds = price_feed_provider.get_price_feed_snapshot()

        assets = {a["asset"]: a for a in overview.get("assets", [])}
        top_gainers = overview.get("top_gainers", [])
        top_losers = overview.get("top_losers", [])
        sentiment = overview.get("sentiment", "MODERATE_RISK_ON")

        btc = assets.get("BTC", {"price": 63450.0, "priceChangePercent": 3.15})
        eth = assets.get("ETH", {"price": 2720.0, "priceChangePercent": -2.45})
        sol = assets.get("SOL", {"price": 164.8, "priceChangePercent": 9.42})
        sui = assets.get("SUI", {"price": 1.82, "priceChangePercent": 14.65})

        top_g = top_gainers[0] if top_gainers else sui

        # 1. Headline
        if btc.get("priceChangePercent", 0) >= 0:
            headline = (
                f"Crypto Markets Advance: {top_g['asset']} (+{top_g['priceChangePercent']:.1f}%) "
                f"and SOL Lead Altcoin Rally as BTC Stabilizes at ${btc['price']:,.0f}"
            )
        else:
            headline = (
                f"Market Choppiness: BTC Tests ${btc['price']:,.0f} While {top_g['asset']} "
                f"Defies Trend with +{top_g['priceChangePercent']:.1f}% Surge"
            )

        # 2. Key Points
        gainers_str = ", ".join(f"{g['asset']} (+{g['priceChangePercent']:.1f}%)" for g in top_gainers[:2])
        losers_str = ", ".join(f"{l['asset']} ({l['priceChangePercent']:.1f}%)" for l in top_losers)
        bnb_daily_m = price_feeds['bnb_chain']['daily_transactions'] / 1e6
        bnb_gas = price_feeds['bnb_chain']['gas_gwei']
        eth_gas = price_feeds['ethereum']['gas_gwei']
        whale_flow_label = price_feeds['whale_flow']['net_exchange_flow'].lower().replace('_', ' ')
        whale_outflow_m = price_feeds['whale_flow']['net_outflow_usd'] / 1e6

        key_points = [
            f"Bitcoin (BTC) is trading at ${btc['price']:,.2f} ({btc['priceChangePercent']:+.2f}%), consolidating above key support as volume holds steady.",
            f"Top performers: {gainers_str} demonstrate strong selective altcoin momentum.",
            f"Laggards: {losers_str} faced localized profit taking.",
            f"Market indicators: BNB Chain recorded {bnb_daily_m:.1f}M daily txs with gas at {bnb_gas} Gwei; Ethereum mainnet gas averaged {eth_gas} Gwei.",
            f"Whale flows show {whale_flow_label} (${whale_outflow_m:.0f}M), pointing to continued institutional spot accumulation.",
        ]

        # 3. Compact Metrics
        metrics = {
            "btc_price": btc["price"],
            "btc_change_24h": btc["priceChangePercent"],
            "eth_price": eth["price"],
            "eth_change_24h": eth["priceChangePercent"],
            "sol_price": sol["price"],
            "sol_change_24h": sol["priceChangePercent"],
            "top_gainer_asset": top_g["asset"],
            "top_gainer_pct": top_g["priceChangePercent"],
            "bnb_txs": f"{price_feeds['bnb_chain']['daily_transactions'] / 1e6:.1f}M",
            "bnb_gas": f"{price_feeds['bnb_chain']['gas_gwei']}",
            "eth_gas": f"{price_feeds['ethereum']['gas_gwei']}",
            "eth_dex_vol": f"{price_feeds['ethereum']['dex_volume_24h_usd'] / 1e9:.2f}B",
            "tvl_usd": f"{price_feeds['defi_pulse']['total_tvl_usd'] / 1e9:.1f}B",
            "tvl_change": f"+{price_feeds['defi_pulse']['tvl_24h_change_pct']:.1f}%",
            "whale_signal": f"{price_feeds['whale_flow']['net_exchange_flow']} (${price_feeds['whale_flow']['net_outflow_usd'] / 1e6:.0f}M)",
        }

        return MarketBrief(
            headline=headline,
            sentiment=sentiment,
            key_points=key_points,
            top_gainers=top_gainers,
            top_losers=top_losers,
            metrics=metrics,
        )
